/* OpenAction 1.0-rc1 reference SDK — zero dependencies. */
(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.OpenAction=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  const VERSION='1.0-rc1';
  const TRANSITIONS={proposed:['ready','cancelled'],ready:['approved','cancelled','expired'],approved:['executing','cancelled','expired'],executing:['succeeded','failed'],succeeded:[],failed:[],cancelled:[],expired:[]};
  const RISKS=new Set(['low','medium','high','critical']);
  const uid=(p='oa')=>`${p}_${(typeof crypto!=='undefined'&&crypto.randomUUID)?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now().toString(36)}`;
  const clone=x=>typeof structuredClone==='function'?structuredClone(x):JSON.parse(JSON.stringify(x));
  function evidence(x){if(typeof x==='string')x={kind:'other',source:x};return {id:x.id||uid('ev'),kind:x.kind||'other',source:x.source||'unknown',...(x.excerpt?{excerpt:x.excerpt}:{}),...(x.uri?{uri:x.uri}:{}),...(x.locator?{locator:x.locator}:{}),...(x.sensitivity?{sensitivity:x.sensitivity}:{})};}
  function create(input){if(!input?.kind||!input?.label||!input?.reason)throw new Error('kind, label and reason are required');const risk=input.risk||'low';if(!RISKS.has(risk))throw new Error('invalid risk');const high=['high','critical'].includes(risk);const approval=input.approval||{required:high,mode:high?'qualified_human':'none',status:high?'pending':'not_required'};if(high&&(!approval.required||!['human','qualified_human'].includes(approval.mode)))throw new Error('high/critical actions require human approval');return {openaction:VERSION,id:input.id||uid('oa'),...(input.case_id?{case_id:input.case_id}:{}),kind:input.kind,label:input.label,status:input.status||'proposed',reason:input.reason,actor:input.actor||{type:'service',id:'local'},...(input.target?{target:input.target}:{}),...(input.inputs?{inputs:input.inputs}:{}),created_at:input.created_at||new Date().toISOString(),evidence:(input.evidence||[]).map(evidence),risk,permissions:input.permissions||[],approval,reversible:Boolean(input.reversible),...(input.idempotency_key?{idempotency_key:input.idempotency_key}:{}),...(input.correlation_id?{correlation_id:input.correlation_id}:{}),...(input.extensions?{extensions:input.extensions}:{})};}
  function validate(a){const errors=[];if(a?.openaction!==VERSION)errors.push('openaction must be 1.0-rc1');if(!a?.id?.startsWith('oa_'))errors.push('id must start oa_');if(!a?.kind?.includes('.'))errors.push('kind must be namespaced');if(!a?.created_at)errors.push('created_at required');if(!Array.isArray(a?.evidence)||!a.evidence.length)errors.push('evidence required');if(!Array.isArray(a?.permissions))errors.push('permissions must be array');if(!RISKS.has(a?.risk))errors.push('invalid risk');if(['high','critical'].includes(a?.risk)&&(!a?.approval?.required||!['human','qualified_human'].includes(a?.approval?.mode)))errors.push('high/critical requires human approval');if(['approved','executing','succeeded'].includes(a?.status)&&a?.approval?.status!=='approved')errors.push('approved/executing/succeeded requires approved approval');return {ok:errors.length===0,errors};}
  function transition(a,next){const copy=clone(a);if(!(TRANSITIONS[copy.status]||[]).includes(next))throw new Error(`invalid transition ${copy.status} -> ${next}`);copy.status=next;copy.updated_at=new Date().toISOString();return copy;}
  function applyReceipt(a,receipt){if(receipt?.decision!=='approved')throw new Error('approved receipt required');if(receipt?.scope?.subject!==a.id&&receipt?.scope?.subject!==a.kind)throw new Error('receipt scope mismatch');const copy=clone(a);copy.approval={...copy.approval,required:true,status:'approved',receipt_id:receipt.id,expires_at:receipt.expires_at,conditions:receipt.conditions||[]};if(copy.status==='ready')copy.status='approved';copy.updated_at=new Date().toISOString();return copy;}
  function complete(a,outcome){const copy=clone(a);if(copy.status!=='executing'&&copy.status!=='approved')throw new Error('action must be approved/executing');copy.status=outcome?.status==='failed'?'failed':'succeeded';copy.outcome={status:outcome?.status||'succeeded',summary:outcome?.summary||'Completed',completed_at:new Date().toISOString(),...(outcome?.receipt?{receipt:outcome.receipt}:{}),...(outcome?.metrics?{metrics:outcome.metrics}:{})};return copy;}
  function toCloudEvent(a,source='urn:openaction:local'){return {specversion:'1.0',id:uid('evt'),source,type:`org.openaction.action.${a.status}`,time:new Date().toISOString(),datacontenttype:'application/vnd.openaction+json',openactionversion:VERSION,subject:a.id,data:a};}
  function impact(changes,gates=[]){const dims=new Set(changes.map(c=>c.dimension));return {version:'openaction-change/1.0-rc1',id:uid('oac'),subject:'change-set',changes,gate_impacts:gates.map(g=>{const hit=(g.reopen_on||[]).some(x=>dims.has(x));return {gate_id:g.id,impact:hit?'reopen':'unchanged',reason:hit?'A declared gate assumption changed.':'No declared dependency changed.'};}),generated_at:new Date().toISOString(),human_review_required:true};}
  return {VERSION,TRANSITIONS,create,validate,transition,applyReceipt,complete,toCloudEvent,impact};
});